/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ConfirmIdRouteImport } from './routes/confirm.$id'
import { Route as AppWorkStopRightRouteImport } from './routes/_app/work-stop-right'
import { Route as AppWorkStopRecordsRouteImport } from './routes/_app/work-stop-records'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNearMissRouteImport } from './routes/_app/near-miss'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConsoleRouteImport } from './routes/_app/console'
import { Route as AppNearMissNewRouteImport } from './routes/_app/near-miss.new'
import { Route as AppNearMissIdRouteImport } from './routes/_app/near-miss.$id'
import { Route as AppAssessmentNewRouteImport } from './routes/_app/assessment.new'
import { Route as AppAssessmentIdIndexRouteImport } from './routes/_app/assessment.$id.index'
import { Route as AppAssessmentIdShareRouteImport } from './routes/_app/assessment.$id.share'
import { Route as AppAssessmentIdResultsRouteImport } from './routes/_app/assessment.$id.results'
import { Route as AppAssessmentIdReportRouteImport } from './routes/_app/assessment.$id.report'
import { Route as AppAssessmentIdMeasuresRouteImport } from './routes/_app/assessment.$id.measures'
import { Route as AppAssessmentIdHazardsRouteImport } from './routes/_app/assessment.$id.hazards'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmIdRoute = ConfirmIdRouteImport.update({
  id: '/confirm/$id',
  path: '/confirm/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkStopRightRoute = AppWorkStopRightRouteImport.update({
  id: '/work-stop-right',
  path: '/work-stop-right',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkStopRecordsRoute = AppWorkStopRecordsRouteImport.update({
  id: '/work-stop-records',
  path: '/work-stop-records',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNearMissRoute = AppNearMissRouteImport.update({
  id: '/near-miss',
  path: '/near-miss',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleRoute = AppConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppRoute,
} as any)
const AppNearMissNewRoute = AppNearMissNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppNearMissRoute,
} as any)
const AppNearMissIdRoute = AppNearMissIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNearMissRoute,
} as any)
const AppAssessmentNewRoute = AppAssessmentNewRouteImport.update({
  id: '/assessment/new',
  path: '/assessment/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIdIndexRoute = AppAssessmentIdIndexRouteImport.update({
  id: '/assessment/$id/',
  path: '/assessment/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIdShareRoute = AppAssessmentIdShareRouteImport.update({
  id: '/assessment/$id/share',
  path: '/assessment/$id/share',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIdResultsRoute = AppAssessmentIdResultsRouteImport.update({
  id: '/assessment/$id/results',
  path: '/assessment/$id/results',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIdReportRoute = AppAssessmentIdReportRouteImport.update({
  id: '/assessment/$id/report',
  path: '/assessment/$id/report',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIdMeasuresRoute = AppAssessmentIdMeasuresRouteImport.update({
  id: '/assessment/$id/measures',
  path: '/assessment/$id/measures',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIdHazardsRoute = AppAssessmentIdHazardsRouteImport.update({
  id: '/assessment/$id/hazards',
  path: '/assessment/$id/hazards',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/console': typeof AppConsoleRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/near-miss': typeof AppNearMissRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/work-stop-records': typeof AppWorkStopRecordsRoute
  '/work-stop-right': typeof AppWorkStopRightRoute
  '/confirm/$id': typeof ConfirmIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/assessment/new': typeof AppAssessmentNewRoute
  '/near-miss/$id': typeof AppNearMissIdRoute
  '/near-miss/new': typeof AppNearMissNewRoute
  '/assessment/$id/hazards': typeof AppAssessmentIdHazardsRoute
  '/assessment/$id/measures': typeof AppAssessmentIdMeasuresRoute
  '/assessment/$id/report': typeof AppAssessmentIdReportRoute
  '/assessment/$id/results': typeof AppAssessmentIdResultsRoute
  '/assessment/$id/share': typeof AppAssessmentIdShareRoute
  '/assessment/$id/': typeof AppAssessmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/console': typeof AppConsoleRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/near-miss': typeof AppNearMissRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/work-stop-records': typeof AppWorkStopRecordsRoute
  '/work-stop-right': typeof AppWorkStopRightRoute
  '/confirm/$id': typeof ConfirmIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/assessment/new': typeof AppAssessmentNewRoute
  '/near-miss/$id': typeof AppNearMissIdRoute
  '/near-miss/new': typeof AppNearMissNewRoute
  '/assessment/$id/hazards': typeof AppAssessmentIdHazardsRoute
  '/assessment/$id/measures': typeof AppAssessmentIdMeasuresRoute
  '/assessment/$id/report': typeof AppAssessmentIdReportRoute
  '/assessment/$id/results': typeof AppAssessmentIdResultsRoute
  '/assessment/$id/share': typeof AppAssessmentIdShareRoute
  '/assessment/$id': typeof AppAssessmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/console': typeof AppConsoleRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/near-miss': typeof AppNearMissRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/work-stop-records': typeof AppWorkStopRecordsRoute
  '/_app/work-stop-right': typeof AppWorkStopRightRoute
  '/confirm/$id': typeof ConfirmIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/assessment/new': typeof AppAssessmentNewRoute
  '/_app/near-miss/$id': typeof AppNearMissIdRoute
  '/_app/near-miss/new': typeof AppNearMissNewRoute
  '/_app/assessment/$id/hazards': typeof AppAssessmentIdHazardsRoute
  '/_app/assessment/$id/measures': typeof AppAssessmentIdMeasuresRoute
  '/_app/assessment/$id/report': typeof AppAssessmentIdReportRoute
  '/_app/assessment/$id/results': typeof AppAssessmentIdResultsRoute
  '/_app/assessment/$id/share': typeof AppAssessmentIdShareRoute
  '/_app/assessment/$id/': typeof AppAssessmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/console'
    | '/dashboard'
    | '/history'
    | '/near-miss'
    | '/settings'
    | '/team'
    | '/work-stop-records'
    | '/work-stop-right'
    | '/confirm/$id'
    | '/invite/$token'
    | '/assessment/new'
    | '/near-miss/$id'
    | '/near-miss/new'
    | '/assessment/$id/hazards'
    | '/assessment/$id/measures'
    | '/assessment/$id/report'
    | '/assessment/$id/results'
    | '/assessment/$id/share'
    | '/assessment/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/console'
    | '/dashboard'
    | '/history'
    | '/near-miss'
    | '/settings'
    | '/team'
    | '/work-stop-records'
    | '/work-stop-right'
    | '/confirm/$id'
    | '/invite/$token'
    | '/assessment/new'
    | '/near-miss/$id'
    | '/near-miss/new'
    | '/assessment/$id/hazards'
    | '/assessment/$id/measures'
    | '/assessment/$id/report'
    | '/assessment/$id/results'
    | '/assessment/$id/share'
    | '/assessment/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signup'
    | '/_app/console'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/near-miss'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/work-stop-records'
    | '/_app/work-stop-right'
    | '/confirm/$id'
    | '/invite/$token'
    | '/_app/assessment/new'
    | '/_app/near-miss/$id'
    | '/_app/near-miss/new'
    | '/_app/assessment/$id/hazards'
    | '/_app/assessment/$id/measures'
    | '/_app/assessment/$id/report'
    | '/_app/assessment/$id/results'
    | '/_app/assessment/$id/share'
    | '/_app/assessment/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignupRoute: typeof SignupRoute
  ConfirmIdRoute: typeof ConfirmIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$id': {
      id: '/confirm/$id'
      path: '/confirm/$id'
      fullPath: '/confirm/$id'
      preLoaderRoute: typeof ConfirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/work-stop-right': {
      id: '/_app/work-stop-right'
      path: '/work-stop-right'
      fullPath: '/work-stop-right'
      preLoaderRoute: typeof AppWorkStopRightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-stop-records': {
      id: '/_app/work-stop-records'
      path: '/work-stop-records'
      fullPath: '/work-stop-records'
      preLoaderRoute: typeof AppWorkStopRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/near-miss': {
      id: '/_app/near-miss'
      path: '/near-miss'
      fullPath: '/near-miss'
      preLoaderRoute: typeof AppNearMissRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/console': {
      id: '/_app/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AppConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/near-miss/new': {
      id: '/_app/near-miss/new'
      path: '/new'
      fullPath: '/near-miss/new'
      preLoaderRoute: typeof AppNearMissNewRouteImport
      parentRoute: typeof AppNearMissRoute
    }
    '/_app/near-miss/$id': {
      id: '/_app/near-miss/$id'
      path: '/$id'
      fullPath: '/near-miss/$id'
      preLoaderRoute: typeof AppNearMissIdRouteImport
      parentRoute: typeof AppNearMissRoute
    }
    '/_app/assessment/new': {
      id: '/_app/assessment/new'
      path: '/assessment/new'
      fullPath: '/assessment/new'
      preLoaderRoute: typeof AppAssessmentNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/$id/': {
      id: '/_app/assessment/$id/'
      path: '/assessment/$id'
      fullPath: '/assessment/$id/'
      preLoaderRoute: typeof AppAssessmentIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/$id/share': {
      id: '/_app/assessment/$id/share'
      path: '/assessment/$id/share'
      fullPath: '/assessment/$id/share'
      preLoaderRoute: typeof AppAssessmentIdShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/$id/results': {
      id: '/_app/assessment/$id/results'
      path: '/assessment/$id/results'
      fullPath: '/assessment/$id/results'
      preLoaderRoute: typeof AppAssessmentIdResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/$id/report': {
      id: '/_app/assessment/$id/report'
      path: '/assessment/$id/report'
      fullPath: '/assessment/$id/report'
      preLoaderRoute: typeof AppAssessmentIdReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/$id/measures': {
      id: '/_app/assessment/$id/measures'
      path: '/assessment/$id/measures'
      fullPath: '/assessment/$id/measures'
      preLoaderRoute: typeof AppAssessmentIdMeasuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/$id/hazards': {
      id: '/_app/assessment/$id/hazards'
      path: '/assessment/$id/hazards'
      fullPath: '/assessment/$id/hazards'
      preLoaderRoute: typeof AppAssessmentIdHazardsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppNearMissRouteChildren {
  AppNearMissIdRoute: typeof AppNearMissIdRoute
  AppNearMissNewRoute: typeof AppNearMissNewRoute
}

const AppNearMissRouteChildren: AppNearMissRouteChildren = {
  AppNearMissIdRoute: AppNearMissIdRoute,
  AppNearMissNewRoute: AppNearMissNewRoute,
}

const AppNearMissRouteWithChildren = AppNearMissRoute._addFileChildren(
  AppNearMissRouteChildren,
)

interface AppRouteChildren {
  AppConsoleRoute: typeof AppConsoleRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNearMissRoute: typeof AppNearMissRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWorkStopRecordsRoute: typeof AppWorkStopRecordsRoute
  AppWorkStopRightRoute: typeof AppWorkStopRightRoute
  AppAssessmentNewRoute: typeof AppAssessmentNewRoute
  AppAssessmentIdHazardsRoute: typeof AppAssessmentIdHazardsRoute
  AppAssessmentIdMeasuresRoute: typeof AppAssessmentIdMeasuresRoute
  AppAssessmentIdReportRoute: typeof AppAssessmentIdReportRoute
  AppAssessmentIdResultsRoute: typeof AppAssessmentIdResultsRoute
  AppAssessmentIdShareRoute: typeof AppAssessmentIdShareRoute
  AppAssessmentIdIndexRoute: typeof AppAssessmentIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConsoleRoute: AppConsoleRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNearMissRoute: AppNearMissRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWorkStopRecordsRoute: AppWorkStopRecordsRoute,
  AppWorkStopRightRoute: AppWorkStopRightRoute,
  AppAssessmentNewRoute: AppAssessmentNewRoute,
  AppAssessmentIdHazardsRoute: AppAssessmentIdHazardsRoute,
  AppAssessmentIdMeasuresRoute: AppAssessmentIdMeasuresRoute,
  AppAssessmentIdReportRoute: AppAssessmentIdReportRoute,
  AppAssessmentIdResultsRoute: AppAssessmentIdResultsRoute,
  AppAssessmentIdShareRoute: AppAssessmentIdShareRoute,
  AppAssessmentIdIndexRoute: AppAssessmentIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignupRoute: SignupRoute,
  ConfirmIdRoute: ConfirmIdRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
